/*
 * This file is generated by jOOQ.
 */
package com.hedera.hashgraph.seven_twenty_one.contract.db.routines;


import com.hedera.hashgraph.seven_twenty_one.contract.db.Public;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ToUnixNano extends AbstractRoutine<Long> {

    private static final long serialVersionUID = 323173958;

    /**
     * The parameter <code>public.to_unix_nano.RETURN_VALUE</code>.
     */
    public static final Parameter<Long> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>public.to_unix_nano.ts</code>.
     */
    public static final Parameter<LocalDateTime> TS = Internal.createParameter("ts", org.jooq.impl.SQLDataType.LOCALDATETIME, false, false);

    /**
     * Create a new routine call instance
     */
    public ToUnixNano() {
        super("to_unix_nano", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

        setReturnParameter(RETURN_VALUE);
        addInParameter(TS);
    }

    /**
     * Set the <code>ts</code> parameter IN value to the routine
     */
    public void setTs(LocalDateTime value) {
        setValue(TS, value);
    }

    /**
     * Set the <code>ts</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setTs(Field<LocalDateTime> field) {
        setField(TS, field);
    }
}
