/*
 * This file is generated by jOOQ.
 */
package com.hedera.hashgraph.seven_twenty_one.contract.db.routines;


import com.hedera.hashgraph.seven_twenty_one.contract.db.Public;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UnixNanoInterval extends AbstractRoutine<Long> {

    private static final long serialVersionUID = -1872040256;

    /**
     * The parameter <code>public.unix_nano_interval.RETURN_VALUE</code>.
     */
    public static final Parameter<Long> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>public.unix_nano_interval.ival</code>.
     */
    public static final Parameter<String> IVAL = Internal.createParameter("ival", org.jooq.impl.SQLDataType.CLOB, false, false);

    /**
     * Create a new routine call instance
     */
    public UnixNanoInterval() {
        super("unix_nano_interval", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

        setReturnParameter(RETURN_VALUE);
        addInParameter(IVAL);
    }

    /**
     * Set the <code>ival</code> parameter IN value to the routine
     */
    public void setIval(String value) {
        setValue(IVAL, value);
    }

    /**
     * Set the <code>ival</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setIval(Field<String> field) {
        setField(IVAL, field);
    }
}
