/*
 * This file is generated by jOOQ.
 */
package com.hedera.hashgraph.seven_twenty_one.contract.db;


import com.hedera.hashgraph.seven_twenty_one.contract.db.tables.Event;
import com.hedera.hashgraph.seven_twenty_one.contract.db.tables.FlywaySchemaHistory;
import com.hedera.hashgraph.seven_twenty_one.contract.db.tables.Transaction;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index EVENT_EVENT_IDX = Indexes0.EVENT_EVENT_IDX;
    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Indexes0.FLYWAY_SCHEMA_HISTORY_S_IDX;
    public static final Index TRANSACTION_FUNCTION_IDX = Indexes0.TRANSACTION_FUNCTION_IDX;
    public static final Index TRANSACTION_HEDERA_OPERATOR_ACCOUNT_NUM_HEDERA_VALID_START__IDX = Indexes0.TRANSACTION_HEDERA_OPERATOR_ACCOUNT_NUM_HEDERA_VALID_START__IDX;
    public static final Index TRANSACTION_STATUS_IDX = Indexes0.TRANSACTION_STATUS_IDX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index EVENT_EVENT_IDX = Internal.createIndex("event_event_idx", Event.EVENT, new OrderField[] { Event.EVENT.EVENT_ }, false);
        public static Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex("flyway_schema_history_s_idx", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
        public static Index TRANSACTION_FUNCTION_IDX = Internal.createIndex("transaction_function_idx", Transaction.TRANSACTION, new OrderField[] { Transaction.TRANSACTION.FUNCTION }, false);
        public static Index TRANSACTION_HEDERA_OPERATOR_ACCOUNT_NUM_HEDERA_VALID_START__IDX = Internal.createIndex("transaction_hedera_operator_account_num_hedera_valid_start__idx", Transaction.TRANSACTION, new OrderField[] { Transaction.TRANSACTION.HEDERA_OPERATOR_ACCOUNT_NUM, Transaction.TRANSACTION.HEDERA_VALID_START_NANOS }, false);
        public static Index TRANSACTION_STATUS_IDX = Internal.createIndex("transaction_status_idx", Transaction.TRANSACTION, new OrderField[] { Transaction.TRANSACTION.STATUS }, false);
    }
}
