/*
 * This file is generated by jOOQ.
 */
package com.hedera.hashgraph.seven_twenty_one.contract.db.tables;


import com.hedera.hashgraph.seven_twenty_one.contract.db.Keys;
import com.hedera.hashgraph.seven_twenty_one.contract.db.Public;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddressTransaction extends TableImpl<Record> {

    private static final long serialVersionUID = 1986228282;

    /**
     * The reference instance of <code>public.address_transaction</code>
     */
    public static final AddressTransaction ADDRESS_TRANSACTION = new AddressTransaction();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.address_transaction.address_id</code>.
     */
    public final TableField<Record, Long> ADDRESS_ID = createField(DSL.name("address_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.address_transaction.transaction_timestamp</code>.
     */
    public final TableField<Record, Long> TRANSACTION_TIMESTAMP = createField(DSL.name("transaction_timestamp"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>public.address_transaction</code> table reference
     */
    public AddressTransaction() {
        this(DSL.name("address_transaction"), null);
    }

    /**
     * Create an aliased <code>public.address_transaction</code> table reference
     */
    public AddressTransaction(String alias) {
        this(DSL.name(alias), ADDRESS_TRANSACTION);
    }

    /**
     * Create an aliased <code>public.address_transaction</code> table reference
     */
    public AddressTransaction(Name alias) {
        this(alias, ADDRESS_TRANSACTION);
    }

    private AddressTransaction(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private AddressTransaction(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> AddressTransaction(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, ADDRESS_TRANSACTION);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.ADDRESS_TRANSACTION_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.ADDRESS_TRANSACTION_PKEY);
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.ADDRESS_TRANSACTION__ADDRESS_TRANSACTION_ADDRESS_ID_FKEY);
    }

    public Address address() {
        return new Address(this, Keys.ADDRESS_TRANSACTION__ADDRESS_TRANSACTION_ADDRESS_ID_FKEY);
    }

    @Override
    public AddressTransaction as(String alias) {
        return new AddressTransaction(DSL.name(alias), this);
    }

    @Override
    public AddressTransaction as(Name alias) {
        return new AddressTransaction(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AddressTransaction rename(String name) {
        return new AddressTransaction(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AddressTransaction rename(Name name) {
        return new AddressTransaction(name, null);
    }
}
