/*
 * This file is generated by jOOQ.
 */
package com.hedera.hashgraph.seven_twenty_one.contract.db.tables;


import com.hedera.hashgraph.seven_twenty_one.contract.db.Keys;
import com.hedera.hashgraph.seven_twenty_one.contract.db.Public;

import java.math.BigInteger;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventTransfer extends TableImpl<Record> {

    private static final long serialVersionUID = 227109255;

    /**
     * The reference instance of <code>public.event_transfer</code>
     */
    public static final EventTransfer EVENT_TRANSFER = new EventTransfer();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.event_transfer.timestamp</code>.
     */
    public final TableField<Record, Long> TIMESTAMP = createField(DSL.name("timestamp"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.event_transfer.from_address_id</code>.
     */
    public final TableField<Record, Long> FROM_ADDRESS_ID = createField(DSL.name("from_address_id"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.event_transfer.to_address_id</code>.
     */
    public final TableField<Record, Long> TO_ADDRESS_ID = createField(DSL.name("to_address_id"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.event_transfer.token_id</code>.
     */
    public final TableField<Record, BigInteger> TOKEN_ID = createField(DSL.name("token_id"), org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(78).nullable(false), this, "");

    /**
     * Create a <code>public.event_transfer</code> table reference
     */
    public EventTransfer() {
        this(DSL.name("event_transfer"), null);
    }

    /**
     * Create an aliased <code>public.event_transfer</code> table reference
     */
    public EventTransfer(String alias) {
        this(DSL.name(alias), EVENT_TRANSFER);
    }

    /**
     * Create an aliased <code>public.event_transfer</code> table reference
     */
    public EventTransfer(Name alias) {
        this(alias, EVENT_TRANSFER);
    }

    private EventTransfer(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private EventTransfer(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> EventTransfer(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, EVENT_TRANSFER);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.EVENT_TRANSFER_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.EVENT_TRANSFER_PKEY);
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.EVENT_TRANSFER__EVENT_TRANSFER_FROM_ADDRESS_ID_FKEY, Keys.EVENT_TRANSFER__EVENT_TRANSFER_TO_ADDRESS_ID_FKEY);
    }

    public Address eventTransferFromAddressIdFkey() {
        return new Address(this, Keys.EVENT_TRANSFER__EVENT_TRANSFER_FROM_ADDRESS_ID_FKEY);
    }

    public Address eventTransferToAddressIdFkey() {
        return new Address(this, Keys.EVENT_TRANSFER__EVENT_TRANSFER_TO_ADDRESS_ID_FKEY);
    }

    @Override
    public EventTransfer as(String alias) {
        return new EventTransfer(DSL.name(alias), this);
    }

    @Override
    public EventTransfer as(Name alias) {
        return new EventTransfer(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public EventTransfer rename(String name) {
        return new EventTransfer(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EventTransfer rename(Name name) {
        return new EventTransfer(name, null);
    }
}
