/*
 * This file is generated by jOOQ.
 */
package com.hedera.hashgraph.seven_twenty_one.contract.db.tables;


import com.hedera.hashgraph.seven_twenty_one.contract.db.Keys;
import com.hedera.hashgraph.seven_twenty_one.contract.db.Public;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventConstructed extends TableImpl<Record> {

    private static final long serialVersionUID = 1207317533;

    /**
     * The reference instance of <code>public.event_constructed</code>
     */
    public static final EventConstructed EVENT_CONSTRUCTED = new EventConstructed();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.event_constructed.timestamp</code>.
     */
    public final TableField<Record, Long> TIMESTAMP = createField(DSL.name("timestamp"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.event_constructed.token_name</code>.
     */
    public final TableField<Record, String> TOKEN_NAME = createField(DSL.name("token_name"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.event_constructed.token_symbol</code>.
     */
    public final TableField<Record, String> TOKEN_SYMBOL = createField(DSL.name("token_symbol"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>public.event_constructed</code> table reference
     */
    public EventConstructed() {
        this(DSL.name("event_constructed"), null);
    }

    /**
     * Create an aliased <code>public.event_constructed</code> table reference
     */
    public EventConstructed(String alias) {
        this(DSL.name(alias), EVENT_CONSTRUCTED);
    }

    /**
     * Create an aliased <code>public.event_constructed</code> table reference
     */
    public EventConstructed(Name alias) {
        this(alias, EVENT_CONSTRUCTED);
    }

    private EventConstructed(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private EventConstructed(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> EventConstructed(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, EVENT_CONSTRUCTED);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.EVENT_CONSTRUCTED_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.EVENT_CONSTRUCTED_PKEY);
    }

    @Override
    public EventConstructed as(String alias) {
        return new EventConstructed(DSL.name(alias), this);
    }

    @Override
    public EventConstructed as(Name alias) {
        return new EventConstructed(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public EventConstructed rename(String name) {
        return new EventConstructed(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EventConstructed rename(Name name) {
        return new EventConstructed(name, null);
    }
}
