/*
 * This file is generated by jOOQ.
 */
package com.hedera.hashgraph.seven_twenty_one.contract.db.tables;


import com.hedera.hashgraph.seven_twenty_one.contract.db.Keys;
import com.hedera.hashgraph.seven_twenty_one.contract.db.Public;

import java.math.BigInteger;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventApproval extends TableImpl<Record> {

    private static final long serialVersionUID = -868999245;

    /**
     * The reference instance of <code>public.event_approval</code>
     */
    public static final EventApproval EVENT_APPROVAL = new EventApproval();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.event_approval.timestamp</code>.
     */
    public final TableField<Record, Long> TIMESTAMP = createField(DSL.name("timestamp"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.event_approval.owner_address_id</code>.
     */
    public final TableField<Record, Long> OWNER_ADDRESS_ID = createField(DSL.name("owner_address_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.event_approval.approved_address_id</code>.
     */
    public final TableField<Record, Long> APPROVED_ADDRESS_ID = createField(DSL.name("approved_address_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.event_approval.token_id</code>.
     */
    public final TableField<Record, BigInteger> TOKEN_ID = createField(DSL.name("token_id"), org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(78).nullable(false), this, "");

    /**
     * Create a <code>public.event_approval</code> table reference
     */
    public EventApproval() {
        this(DSL.name("event_approval"), null);
    }

    /**
     * Create an aliased <code>public.event_approval</code> table reference
     */
    public EventApproval(String alias) {
        this(DSL.name(alias), EVENT_APPROVAL);
    }

    /**
     * Create an aliased <code>public.event_approval</code> table reference
     */
    public EventApproval(Name alias) {
        this(alias, EVENT_APPROVAL);
    }

    private EventApproval(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private EventApproval(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> EventApproval(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, EVENT_APPROVAL);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.EVENT_APPROVAL_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.EVENT_APPROVAL_PKEY);
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.EVENT_APPROVAL__EVENT_APPROVAL_OWNER_ADDRESS_ID_FKEY, Keys.EVENT_APPROVAL__EVENT_APPROVAL_APPROVED_ADDRESS_ID_FKEY);
    }

    public Address eventApprovalOwnerAddressIdFkey() {
        return new Address(this, Keys.EVENT_APPROVAL__EVENT_APPROVAL_OWNER_ADDRESS_ID_FKEY);
    }

    public Address eventApprovalApprovedAddressIdFkey() {
        return new Address(this, Keys.EVENT_APPROVAL__EVENT_APPROVAL_APPROVED_ADDRESS_ID_FKEY);
    }

    @Override
    public EventApproval as(String alias) {
        return new EventApproval(DSL.name(alias), this);
    }

    @Override
    public EventApproval as(Name alias) {
        return new EventApproval(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public EventApproval rename(String name) {
        return new EventApproval(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EventApproval rename(Name name) {
        return new EventApproval(name, null);
    }
}
