/*
 * This file is generated by jOOQ.
 */
package com.hedera.hashgraph.seven_twenty_one.contract.db.tables;


import com.hedera.hashgraph.seven_twenty_one.contract.db.Keys;
import com.hedera.hashgraph.seven_twenty_one.contract.db.Public;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransactionConstructor extends TableImpl<Record> {

    private static final long serialVersionUID = -1047023315;

    /**
     * The reference instance of <code>public.transaction_constructor</code>
     */
    public static final TransactionConstructor TRANSACTION_CONSTRUCTOR = new TransactionConstructor();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.transaction_constructor.timestamp</code>.
     */
    public final TableField<Record, Long> TIMESTAMP = createField(DSL.name("timestamp"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.transaction_constructor.token_name</code>.
     */
    public final TableField<Record, String> TOKEN_NAME = createField(DSL.name("token_name"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.transaction_constructor.token_symbol</code>.
     */
    public final TableField<Record, String> TOKEN_SYMBOL = createField(DSL.name("token_symbol"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.transaction_constructor.base_uri</code>.
     */
    public final TableField<Record, String> BASE_URI = createField(DSL.name("base_uri"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.transaction_constructor</code> table reference
     */
    public TransactionConstructor() {
        this(DSL.name("transaction_constructor"), null);
    }

    /**
     * Create an aliased <code>public.transaction_constructor</code> table reference
     */
    public TransactionConstructor(String alias) {
        this(DSL.name(alias), TRANSACTION_CONSTRUCTOR);
    }

    /**
     * Create an aliased <code>public.transaction_constructor</code> table reference
     */
    public TransactionConstructor(Name alias) {
        this(alias, TRANSACTION_CONSTRUCTOR);
    }

    private TransactionConstructor(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private TransactionConstructor(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> TransactionConstructor(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, TRANSACTION_CONSTRUCTOR);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.TRANSACTION_CONSTRUCTOR_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.TRANSACTION_CONSTRUCTOR_PKEY);
    }

    @Override
    public TransactionConstructor as(String alias) {
        return new TransactionConstructor(DSL.name(alias), this);
    }

    @Override
    public TransactionConstructor as(Name alias) {
        return new TransactionConstructor(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TransactionConstructor rename(String name) {
        return new TransactionConstructor(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TransactionConstructor rename(Name name) {
        return new TransactionConstructor(name, null);
    }
}
