/*
 * This file is generated by jOOQ.
 */
package com.hedera.hashgraph.seven_twenty_one.contract.db.tables;


import com.hedera.hashgraph.seven_twenty_one.contract.db.Keys;
import com.hedera.hashgraph.seven_twenty_one.contract.db.Public;

import java.math.BigInteger;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransactionMint extends TableImpl<Record> {

    private static final long serialVersionUID = 1837130462;

    /**
     * The reference instance of <code>public.transaction_mint</code>
     */
    public static final TransactionMint TRANSACTION_MINT = new TransactionMint();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.transaction_mint.timestamp</code>.
     */
    public final TableField<Record, Long> TIMESTAMP = createField(DSL.name("timestamp"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.transaction_mint.to_address_id</code>.
     */
    public final TableField<Record, Long> TO_ADDRESS_ID = createField(DSL.name("to_address_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.transaction_mint.token_id</code>.
     */
    public final TableField<Record, BigInteger> TOKEN_ID = createField(DSL.name("token_id"), org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(78).nullable(false), this, "");

    /**
     * Create a <code>public.transaction_mint</code> table reference
     */
    public TransactionMint() {
        this(DSL.name("transaction_mint"), null);
    }

    /**
     * Create an aliased <code>public.transaction_mint</code> table reference
     */
    public TransactionMint(String alias) {
        this(DSL.name(alias), TRANSACTION_MINT);
    }

    /**
     * Create an aliased <code>public.transaction_mint</code> table reference
     */
    public TransactionMint(Name alias) {
        this(alias, TRANSACTION_MINT);
    }

    private TransactionMint(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private TransactionMint(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> TransactionMint(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, TRANSACTION_MINT);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.TRANSACTION_MINT_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.TRANSACTION_MINT_PKEY);
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.TRANSACTION_MINT__TRANSACTION_MINT_TO_ADDRESS_ID_FKEY);
    }

    public Address address() {
        return new Address(this, Keys.TRANSACTION_MINT__TRANSACTION_MINT_TO_ADDRESS_ID_FKEY);
    }

    @Override
    public TransactionMint as(String alias) {
        return new TransactionMint(DSL.name(alias), this);
    }

    @Override
    public TransactionMint as(Name alias) {
        return new TransactionMint(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TransactionMint rename(String name) {
        return new TransactionMint(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TransactionMint rename(Name name) {
        return new TransactionMint(name, null);
    }
}
